"""Synthetic knowledge base for the fictional company "Halden Systems".

Every section carries the questions it answers, as (question, expected answer, evidence quote)
triples. The quote is an exact substring of the section body, so evaluation labels are correct
by construction and survive any change of chunk size. Text is ASCII-only so that every format
(including PDF core fonts) renders it identically.
"""

from __future__ import annotations

# (file, collection, roles, title, [(heading, body, [(question, answer, quote)])])
DOCS = [
    (
        "refund-policy.md", "policies", ["employee"], "Customer Refund Policy",
        [
            ("Approval Thresholds",
             "Refunds up to 200 USD may be approved by any support agent without escalation. Refunds between 200 USD and 2,000 USD require approval from a support team lead. Any refund above 2,000 USD must be approved by the Director of Customer Operations and recorded in the finance ledger within two business days.",
             [("Who must approve a customer refund above 2,000 USD?", "The Director of Customer Operations", "Any refund above 2,000 USD must be approved by the Director of Customer Operations"),
              ("What is the largest refund a support agent can approve without escalation?", "200 USD", "Refunds up to 200 USD may be approved by any support agent without escalation")]),
            ("Refund Window",
             "Customers may request a refund within 45 days of the invoice date. Requests received after 45 days are declined unless the account has an active service credit dispute. Annual subscriptions are refunded on a prorated basis for the unused full months.",
             [("How many days after the invoice date can a customer request a refund?", "45 days", "Customers may request a refund within 45 days of the invoice date"),
              ("How are annual subscriptions refunded?", "On a prorated basis for the unused full months", "Annual subscriptions are refunded on a prorated basis for the unused full months")]),
            ("Processing Time",
             "Approved refunds are issued to the original payment method within 7 business days. Refunds to wire transfer customers are processed in the weekly payment run on Thursdays.",
             [("How long does it take for an approved refund to be issued?", "Within 7 business days", "Approved refunds are issued to the original payment method within 7 business days"),
              ("On which day of the week are wire transfer refunds processed?", "Thursdays", "Refunds to wire transfer customers are processed in the weekly payment run on Thursdays")]),
        ],
    ),
    (
        "travel-expense-policy.docx", "policies", ["employee"], "Travel and Expense Policy",
        [
            ("Booking",
             "All air travel must be booked through the Wayfarer Desk travel portal at least 14 days before departure. Economy class is required for flights shorter than 6 hours. Premium economy may be booked for flights of 6 hours or longer.",
             [("How far in advance must air travel be booked?", "At least 14 days before departure", "All air travel must be booked through the Wayfarer Desk travel portal at least 14 days before departure"),
              ("When may premium economy be booked?", "For flights of 6 hours or longer", "Premium economy may be booked for flights of 6 hours or longer")]),
            ("Meals and Lodging",
             "The daily meal allowance is 75 USD for domestic travel and 95 USD for international travel. Hotel stays are capped at 220 USD per night unless the destination is on the high cost city list maintained by Finance.",
             [("What is the daily meal allowance for international travel?", "95 USD", "The daily meal allowance is 75 USD for domestic travel and 95 USD for international travel"),
              ("What is the nightly cap for hotel stays?", "220 USD per night", "Hotel stays are capped at 220 USD per night")]),
            ("Reimbursement",
             "Expense reports must be submitted within 30 days of the end of the trip. Receipts are required for any single expense above 25 USD. Reimbursements are paid with the next payroll cycle after manager approval.",
             [("What is the deadline for submitting an expense report after a trip?", "Within 30 days of the end of the trip", "Expense reports must be submitted within 30 days of the end of the trip"),
              ("Above what amount is a receipt required for an expense?", "25 USD", "Receipts are required for any single expense above 25 USD")]),
        ],
    ),
    (
        "remote-work-policy.html", "policies", ["employee"], "Remote Work Policy",
        [
            ("Eligibility",
             "Employees who have completed their 90 day onboarding period may work remotely up to three days per week. Fully remote arrangements require written approval from the department head and the People team.",
             [("How many days per week may employees work remotely?", "Up to three days per week", "may work remotely up to three days per week"),
              ("Who must approve a fully remote arrangement?", "The department head and the People team", "Fully remote arrangements require written approval from the department head and the People team")]),
            ("Equipment",
             "Halden provides a laptop, a monitor, and a one time home office stipend of 400 USD. The stipend is paid in the first payroll after the remote work agreement is signed.",
             [("How much is the home office stipend?", "400 USD", "a one time home office stipend of 400 USD")]),
            ("Core Hours",
             "Remote employees must be reachable during core collaboration hours from 10:00 to 15:00 in the primary time zone of their team. Meetings outside core hours should be recorded for colleagues who cannot attend.",
             [("What are the core collaboration hours for remote employees?", "10:00 to 15:00 in the primary time zone of their team", "Remote employees must be reachable during core collaboration hours from 10:00 to 15:00")]),
        ],
    ),
    (
        "leave-policy.txt", "policies", ["employee"], "Paid Time Off and Leave Policy",
        [
            ("Annual Leave",
             "Full time employees accrue 24 days of paid annual leave per calendar year. Up to 5 unused days may be carried over into the next year and must be used before March 31.",
             [("How many days of paid annual leave do full time employees accrue per year?", "24 days", "Full time employees accrue 24 days of paid annual leave per calendar year"),
              ("How many unused leave days can be carried over into the next year?", "Up to 5 days", "Up to 5 unused days may be carried over into the next year")]),
            ("Parental Leave",
             "Primary caregivers receive 18 weeks of fully paid parental leave. Secondary caregivers receive 6 weeks of fully paid leave, which may be taken any time within the first year.",
             [("How long is parental leave for primary caregivers?", "18 weeks of fully paid leave", "Primary caregivers receive 18 weeks of fully paid parental leave"),
              ("How many weeks of leave do secondary caregivers receive?", "6 weeks", "Secondary caregivers receive 6 weeks of fully paid leave")]),
            ("Sick Leave",
             "Employees may take up to 10 paid sick days per year. A medical certificate is required for absences longer than 3 consecutive working days.",
             [("When is a medical certificate required for sick leave?", "For absences longer than 3 consecutive working days", "A medical certificate is required for absences longer than 3 consecutive working days")]),
        ],
    ),
    (
        "information-security-policy.pdf", "policies", ["employee"], "Information Security Policy",
        [
            ("Passwords and Authentication",
             "Passwords must be at least 14 characters long and must be stored in the company approved password manager. Multi factor authentication is mandatory for all systems that hold customer data. Hardware security keys are required for administrators.",
             [("What is the minimum password length?", "14 characters", "Passwords must be at least 14 characters long"),
              ("Who is required to use hardware security keys?", "Administrators", "Hardware security keys are required for administrators")]),
            ("Data Classification",
             "Company data is classified into four levels: Public, Internal, Confidential, and Restricted. Restricted data may only be stored in systems approved by the Security Council and must be encrypted at rest and in transit.",
             [("What are the four data classification levels?", "Public, Internal, Confidential, and Restricted", "Company data is classified into four levels: Public, Internal, Confidential, and Restricted")]),
            ("Incident Reporting",
             "Suspected security incidents must be reported to the security hotline within 1 hour of discovery. Lost or stolen devices must be reported immediately so that the device can be remotely wiped.",
             [("How quickly must a suspected security incident be reported?", "Within 1 hour of discovery", "Suspected security incidents must be reported to the security hotline within 1 hour of discovery")]),
        ],
    ),
    (
        "code-of-conduct.md", "policies", ["employee"], "Code of Conduct",
        [
            ("Gifts",
             "Employees may not accept gifts worth more than 50 USD from vendors or customers. Gifts above this value must be declined or handed to the Ethics Office.",
             [("What is the maximum value of a gift an employee may accept from a vendor?", "50 USD", "Employees may not accept gifts worth more than 50 USD from vendors or customers")]),
            ("Conflicts of Interest",
             "Outside employment must be disclosed to the Ethics Office before it begins. Employees may not hold more than a 1 percent ownership stake in a direct competitor.",
             [("How large an ownership stake in a direct competitor may an employee hold?", "No more than 1 percent", "Employees may not hold more than a 1 percent ownership stake in a direct competitor")]),
            ("Reporting Concerns",
             "Concerns can be raised anonymously through the SpeakUp line, which is operated by an independent provider. Retaliation against anyone who reports a concern in good faith is prohibited.",
             [("How can employees raise concerns anonymously?", "Through the SpeakUp line", "Concerns can be raised anonymously through the SpeakUp line")]),
        ],
    ),
    (
        "onboarding-guide.docx", "policies", ["employee"], "New Hire Onboarding Guide",
        [
            ("First Week",
             "New hires receive their laptop and badge on the first day and complete security awareness training within the first 5 working days. Each new hire is paired with an onboarding buddy for the first 60 days.",
             [("For how long is a new hire paired with an onboarding buddy?", "The first 60 days", "Each new hire is paired with an onboarding buddy for the first 60 days"),
              ("By when must new hires complete security awareness training?", "Within the first 5 working days", "complete security awareness training within the first 5 working days")]),
            ("Probation",
             "The probation period lasts 90 days. A formal check in with the manager takes place at day 30 and day 75.",
             [("On which days do the formal probation check ins take place?", "Day 30 and day 75", "A formal check in with the manager takes place at day 30 and day 75")]),
            ("Benefits Enrollment",
             "Health insurance enrollment must be completed within 21 days of the start date. The company matches retirement contributions up to 5 percent of base salary.",
             [("How much of retirement contributions does the company match?", "Up to 5 percent of base salary", "The company matches retirement contributions up to 5 percent of base salary"),
              ("What is the deadline for health insurance enrollment?", "Within 21 days of the start date", "Health insurance enrollment must be completed within 21 days of the start date")]),
        ],
    ),
    (
        "it-helpdesk-guide.html", "policies", ["employee"], "IT Helpdesk Guide",
        [
            ("Support Channels",
             "The IT helpdesk is available on weekdays from 07:00 to 19:00 through the Helpline portal. Urgent outages outside these hours can be reported by phone to the on duty technician.",
             [("What are the opening hours of the IT helpdesk?", "Weekdays from 07:00 to 19:00", "The IT helpdesk is available on weekdays from 07:00 to 19:00")]),
            ("Device Replacement",
             "Laptops are replaced every 36 months. Mobile phones are replaced every 24 months or earlier if the battery health falls below 80 percent.",
             [("How often are laptops replaced?", "Every 36 months", "Laptops are replaced every 36 months")]),
            ("Software Requests",
             "Requests for new software are reviewed by the IT security team within 3 business days. Software that processes customer data also requires a vendor risk assessment.",
             [("How long does the review of a new software request take?", "Within 3 business days", "Requests for new software are reviewed by the IT security team within 3 business days")]),
        ],
    ),
    (
        "customer-support-sla.pdf", "policies", ["employee"], "Customer Support Service Levels",
        [
            ("Response Targets",
             "Priority 1 tickets require a first response within 15 minutes and a status update every hour. Priority 2 tickets require a first response within 2 hours. Priority 3 tickets require a first response within 1 business day.",
             [("What is the first response target for Priority 1 tickets?", "Within 15 minutes", "Priority 1 tickets require a first response within 15 minutes"),
              ("What is the first response target for Priority 2 tickets?", "Within 2 hours", "Priority 2 tickets require a first response within 2 hours")]),
            ("Escalation",
             "A ticket that has been open for more than 48 hours without resolution is escalated to the Tier 3 engineering liaison. Enterprise customers may request escalation directly through their customer success manager.",
             [("After how many hours is an unresolved ticket escalated to Tier 3?", "More than 48 hours", "A ticket that has been open for more than 48 hours without resolution is escalated to the Tier 3 engineering liaison")]),
            ("Service Credits",
             "If monthly uptime falls below 99.9 percent, customers are entitled to a service credit of 10 percent of the monthly fee. Credits must be claimed within 30 days of the incident.",
             [("What service credit do customers get if monthly uptime falls below 99.9 percent?", "10 percent of the monthly fee", "customers are entitled to a service credit of 10 percent of the monthly fee")]),
        ],
    ),
    (
        "performance-review-process.txt", "policies", ["employee"], "Performance Review Process",
        [
            ("Review Cycle",
             "Performance reviews take place twice a year, in June and December. Self assessments are due two weeks before the review meeting.",
             [("In which months do performance reviews take place?", "June and December", "Performance reviews take place twice a year, in June and December")]),
            ("Ratings",
             "Ratings use a five point scale from Needs Improvement to Exceptional. Ratings are calibrated by a panel of at least three managers from the same department.",
             [("Who calibrates performance ratings?", "A panel of at least three managers from the same department", "Ratings are calibrated by a panel of at least three managers from the same department")]),
            ("Promotions",
             "Promotion nominations are submitted by managers in the December cycle. An employee must have at least 12 months in their current level to be eligible.",
             [("How long must an employee be at their current level to be eligible for promotion?", "At least 12 months", "An employee must have at least 12 months in their current level to be eligible")]),
        ],
    ),
    (
        "office-facilities-guide.md", "policies", ["employee"], "Office and Facilities Guide",
        [
            ("Building Access",
             "The headquarters building is open from 06:30 to 21:00 on weekdays. Visitors must be registered in the Lobbyline system at least one day in advance and must be escorted at all times.",
             [("How far in advance must visitors be registered?", "At least one day in advance", "Visitors must be registered in the Lobbyline system at least one day in advance"),
              ("Which system is used to register visitors?", "Lobbyline", "Visitors must be registered in the Lobbyline system")]),
            ("Meeting Rooms",
             "Meeting rooms can be booked up to 60 days ahead. Rooms that are not checked into within 10 minutes of the start time are released automatically.",
             [("After how many minutes is an unused meeting room released?", "10 minutes", "Rooms that are not checked into within 10 minutes of the start time are released automatically")]),
            ("Parking",
             "Parking permits cost 40 USD per month and are deducted from payroll. Electric vehicle charging is free for the first 4 hours per day.",
             [("How much does a parking permit cost?", "40 USD per month", "Parking permits cost 40 USD per month")]),
        ],
    ),
    (
        "finance-budget-fy2026.docx", "policies", ["finance"], "Fiscal Year 2026 Operating Budget",
        [
            ("Budget Overview",
             "The approved operating budget for fiscal year 2026 is 48.2 million USD, an increase of 9 percent over the previous year. Research and development receives the largest allocation at 19.5 million USD.",
             [("What is the approved operating budget for fiscal year 2026?", "48.2 million USD", "The approved operating budget for fiscal year 2026 is 48.2 million USD"),
              ("How much of the fiscal year 2026 budget is allocated to research and development?", "19.5 million USD", "Research and development receives the largest allocation at 19.5 million USD")]),
            ("Headcount Plan",
             "The plan funds 42 net new positions, of which 25 are in engineering. Hiring is frozen for any department that exceeds its quarterly budget by more than 5 percent.",
             [("How many net new positions does the fiscal year 2026 plan fund?", "42", "The plan funds 42 net new positions")]),
            ("Contingency Reserve",
             "A contingency reserve of 2.4 million USD is held centrally and can only be released by the Chief Financial Officer.",
             [("How large is the contingency reserve in the budget?", "2.4 million USD", "A contingency reserve of 2.4 million USD is held centrally")]),
        ],
    ),
    (
        "vendor-payment-procedures.pdf", "policies", ["finance"], "Vendor Payment Procedures",
        [
            ("Payment Terms",
             "Standard payment terms for vendors are net 45 days from receipt of a valid invoice. Early payment within 10 days is permitted when the vendor offers a discount of at least 2 percent.",
             [("What are the standard payment terms for vendors?", "Net 45 days from receipt of a valid invoice", "Standard payment terms for vendors are net 45 days from receipt of a valid invoice")]),
            ("Approval Matrix",
             "Invoices up to 10,000 USD are approved by the budget owner. Invoices between 10,000 USD and 100,000 USD also require the Finance Controller. Invoices above 100,000 USD require the Chief Financial Officer.",
             [("Who must approve vendor invoices above 100,000 USD?", "The Chief Financial Officer", "Invoices above 100,000 USD require the Chief Financial Officer")]),
            ("Payment Runs",
             "Vendor payment runs are executed every Tuesday and Friday. Changes to vendor bank details must be verified by a call back to a known phone number before the next payment.",
             [("On which days are vendor payment runs executed?", "Tuesday and Friday", "Vendor payment runs are executed every Tuesday and Friday")]),
        ],
    ),
    (
        "payroll-calendar.txt", "policies", ["finance"], "Payroll Calendar and Controls",
        [
            ("Payment Schedule",
             "Salaries are paid on the 25th of each month. If the 25th falls on a weekend or public holiday, payment is made on the preceding business day. The payroll cutoff for changes is the 12th of the month.",
             [("On what day of the month are salaries paid?", "The 25th", "Salaries are paid on the 25th of each month"),
              ("What is the payroll cutoff date for changes?", "The 12th of the month", "The payroll cutoff for changes is the 12th of the month")]),
            ("Bonuses",
             "Annual bonuses are paid with the March payroll. The bonus pool for fiscal year 2026 is capped at 3.1 million USD.",
             [("What is the cap on the fiscal year 2026 bonus pool?", "3.1 million USD", "The bonus pool for fiscal year 2026 is capped at 3.1 million USD")]),
            ("Payroll Audit",
             "Payroll records are retained for 7 years. A payroll reconciliation is performed by the Finance Controller within 5 business days of each payment.",
             [("How long are payroll records retained?", "7 years", "Payroll records are retained for 7 years")]),
        ],
    ),
    (
        "quarterly-financial-report-q3.html", "policies", ["finance"], "Third Quarter Financial Report",
        [
            ("Revenue",
             "Revenue for the third quarter was 13.6 million USD, up 11 percent year over year. Subscription revenue accounted for 82 percent of the total.",
             [("What was the revenue in the third quarter?", "13.6 million USD", "Revenue for the third quarter was 13.6 million USD"),
              ("What share of third quarter revenue came from subscriptions?", "82 percent", "Subscription revenue accounted for 82 percent of the total")]),
            ("Costs and Margin",
             "Cloud infrastructure costs rose to 1.9 million USD in the quarter, driven by the migration of the analytics platform. Gross margin was 71 percent.",
             [("What was the gross margin in the third quarter?", "71 percent", "Gross margin was 71 percent")]),
            ("Outlook",
             "Management expects fourth quarter revenue between 14.0 and 14.5 million USD. Net revenue retention is forecast to remain above 108 percent.",
             [("What revenue does management expect for the fourth quarter?", "Between 14.0 and 14.5 million USD", "Management expects fourth quarter revenue between 14.0 and 14.5 million USD")]),
        ],
    ),
    (
        "procurement-policy.md", "policies", ["finance"], "Procurement Policy",
        [
            ("Competitive Bids",
             "Purchases above 25,000 USD require at least three competitive quotes. Sole source purchases must be justified in writing and approved by the Head of Procurement.",
             [("How many competitive quotes are required for purchases above 25,000 USD?", "At least three", "Purchases above 25,000 USD require at least three competitive quotes")]),
            ("Contracts",
             "Contracts longer than 24 months must be reviewed by Legal. Auto renewal clauses are not permitted without a 60 day cancellation notice period.",
             [("Which contracts must be reviewed by Legal?", "Contracts longer than 24 months", "Contracts longer than 24 months must be reviewed by Legal")]),
            ("Corporate Cards",
             "Corporate cards have a default monthly limit of 5,000 USD. Card statements must be reconciled by the 8th of the following month.",
             [("What is the default monthly limit on corporate cards?", "5,000 USD", "Corporate cards have a default monthly limit of 5,000 USD")]),
        ],
    ),
    (
        "incident-response-runbook.md", "engineering", ["engineering"], "Incident Response Runbook",
        [
            ("Severity Levels",
             "A SEV1 incident is a full outage or data loss affecting multiple customers. A SEV2 incident is a major degradation with a workaround. SEV1 incidents must have an incident commander assigned within 10 minutes.",
             [("How quickly must an incident commander be assigned for a SEV1 incident?", "Within 10 minutes", "SEV1 incidents must have an incident commander assigned within 10 minutes")]),
            ("Communication",
             "During a SEV1, the status page must be updated every 30 minutes. All coordination happens in the dedicated incident channel, and the incident commander is the only person who approves external statements.",
             [("How often must the status page be updated during a SEV1 incident?", "Every 30 minutes", "the status page must be updated every 30 minutes")]),
            ("Postmortems",
             "A blameless postmortem must be published within 5 business days of a SEV1 or SEV2 incident. Action items are tracked in the Reliability board until closed.",
             [("What is the deadline for publishing a postmortem after an incident?", "Within 5 business days", "A blameless postmortem must be published within 5 business days of a SEV1 or SEV2 incident")]),
        ],
    ),
    (
        "deployment-guide.txt", "engineering", ["engineering"], "Production Deployment Guide",
        [
            ("Release Process",
             "Production deployments run through the Conveyor pipeline and require two approving reviews. Deployments are frozen from Friday 16:00 until Monday 08:00 unless the change fixes a SEV1 incident.",
             [("How many approving reviews does a production deployment require?", "Two", "Production deployments run through the Conveyor pipeline and require two approving reviews"),
              ("When are production deployments frozen?", "From Friday 16:00 until Monday 08:00", "Deployments are frozen from Friday 16:00 until Monday 08:00")]),
            ("Canary Rollout",
             "Each release is first deployed to a canary group that receives 5 percent of traffic for 30 minutes. The rollout is aborted automatically if the error rate exceeds 1 percent.",
             [("What percentage of traffic does the canary group receive?", "5 percent", "a canary group that receives 5 percent of traffic for 30 minutes"),
              ("At what error rate is a rollout aborted automatically?", "1 percent", "The rollout is aborted automatically if the error rate exceeds 1 percent")]),
            ("Rollback",
             "A rollback must be started within 15 minutes if a release causes a customer facing regression. The previous three release artifacts are always kept available for rollback.",
             [("How many previous release artifacts are kept available for rollback?", "Three", "The previous three release artifacts are always kept available for rollback")]),
        ],
    ),
    (
        "api-style-guide.html", "engineering", ["engineering"], "API Style Guide",
        [
            ("Versioning",
             "Public APIs are versioned in the URL path. A deprecated version must remain available for at least 12 months after the deprecation notice.",
             [("How long must a deprecated API version remain available?", "At least 12 months after the deprecation notice", "A deprecated version must remain available for at least 12 months after the deprecation notice")]),
            ("Pagination",
             "List endpoints use cursor based pagination with a default page size of 50 and a maximum page size of 200.",
             [("What is the maximum page size for list endpoints?", "200", "a default page size of 50 and a maximum page size of 200")]),
            ("Rate Limits",
             "The default rate limit is 600 requests per minute per API key. Clients that exceed the limit receive status code 429 with a retry hint in the response headers.",
             [("What is the default API rate limit?", "600 requests per minute per API key", "The default rate limit is 600 requests per minute per API key"),
              ("Which status code do clients receive when they exceed the rate limit?", "429", "Clients that exceed the limit receive status code 429")]),
        ],
    ),
    (
        "database-operations.pdf", "engineering", ["engineering"], "Database Operations Manual",
        [
            ("Backups",
             "Full database backups run every night at 02:00 UTC and are retained for 35 days. Point in time recovery is available for the last 7 days.",
             [("How long are full database backups retained?", "35 days", "Full database backups run every night at 02:00 UTC and are retained for 35 days"),
              ("For how many days is point in time recovery available?", "The last 7 days", "Point in time recovery is available for the last 7 days")]),
            ("Schema Changes",
             "Schema migrations must be backward compatible with the previous application release. Migrations that lock a table for more than 5 seconds must be run in a maintenance window.",
             [("Which schema migrations must be run in a maintenance window?", "Migrations that lock a table for more than 5 seconds", "Migrations that lock a table for more than 5 seconds must be run in a maintenance window")]),
            ("Production Access",
             "Direct production database access is limited to the database reliability team. All queries run through the Gatekeeper proxy are logged and retained for 400 days.",
             [("How long are query logs from the Gatekeeper proxy retained?", "400 days", "All queries run through the Gatekeeper proxy are logged and retained for 400 days")]),
        ],
    ),
    (
        "oncall-handbook.docx", "engineering", ["engineering"], "On Call Handbook",
        [
            ("Rotation",
             "On call rotations last one week and hand over on Wednesdays at 11:00. Each rotation has a primary and a secondary engineer.",
             [("When do on call rotations hand over?", "Wednesdays at 11:00", "On call rotations last one week and hand over on Wednesdays at 11:00")]),
            ("Response Times",
             "The primary on call engineer must acknowledge a page within 5 minutes. If the page is not acknowledged, it escalates to the secondary after 10 minutes and to the engineering manager after 20 minutes.",
             [("How quickly must the primary on call engineer acknowledge a page?", "Within 5 minutes", "The primary on call engineer must acknowledge a page within 5 minutes")]),
            ("Compensation",
             "Engineers receive a stipend of 350 USD for each week on call. Time worked during an incident outside business hours can be taken back as time off within 30 days.",
             [("What stipend do engineers receive for a week on call?", "350 USD", "Engineers receive a stipend of 350 USD for each week on call")]),
        ],
    ),
    (
        "architecture-overview.md", "engineering", ["engineering"], "Platform Architecture Overview",
        [
            ("Services",
             "The platform consists of 14 services that communicate over gRPC. The order service is the system of record for orders, and the ledger service is the system of record for billing events.",
             [("Which service is the system of record for billing events?", "The ledger service", "the ledger service is the system of record for billing events"),
              ("How many services does the platform consist of?", "14", "The platform consists of 14 services that communicate over gRPC")]),
            ("Messaging",
             "Asynchronous events are published to the Relay message bus with at least once delivery. Consumers must be idempotent and must process an event within 24 hours before it moves to the dead letter queue.",
             [("What delivery guarantee does the Relay message bus provide?", "At least once delivery", "Asynchronous events are published to the Relay message bus with at least once delivery")]),
            ("Data Stores",
             "Transactional data is stored in PostgreSQL 16. Search is served by an OpenSearch cluster with three data nodes, and session data is kept in Redis with a 12 hour expiry.",
             [("What is the expiry of session data kept in Redis?", "12 hours", "session data is kept in Redis with a 12 hour expiry")]),
        ],
    ),
    (
        "secure-coding-standards.txt", "engineering", ["engineering"], "Secure Coding Standards",
        [
            ("Secrets Management",
             "Secrets must never be committed to source control and must be loaded from the Vaultline secrets manager at runtime. Credentials are rotated every 90 days.",
             [("How often are credentials rotated?", "Every 90 days", "Credentials are rotated every 90 days"),
              ("Where must secrets be loaded from at runtime?", "The Vaultline secrets manager", "must be loaded from the Vaultline secrets manager at runtime")]),
            ("Dependencies",
             "Third party dependencies are scanned on every build. Critical vulnerabilities must be patched within 7 days and high vulnerabilities within 30 days.",
             [("How quickly must critical vulnerabilities be patched?", "Within 7 days", "Critical vulnerabilities must be patched within 7 days")]),
            ("Code Review",
             "Every change requires review by at least one engineer who did not write the code. Changes to authentication or payment code also require review by the security team.",
             [("Which code changes require review by the security team?", "Changes to authentication or payment code", "Changes to authentication or payment code also require review by the security team")]),
        ],
    ),
    (
        "engineering-onboarding.html", "engineering", ["employee"], "Engineering Onboarding",
        [
            ("Development Environment",
             "New engineers set up their environment with the bootstrap script, which installs the toolchain in under 20 minutes. The standard development laptop has 32 GB of memory.",
             [("How much memory does the standard development laptop have?", "32 GB", "The standard development laptop has 32 GB of memory")]),
            ("First Tasks",
             "Every new engineer ships a starter task to production within the first 10 working days. Starter tasks are labeled good first issue in the tracker.",
             [("By when should a new engineer ship a starter task to production?", "Within the first 10 working days", "Every new engineer ships a starter task to production within the first 10 working days")]),
            ("Learning Budget",
             "Each engineer has an annual learning budget of 1,500 USD for courses, books, and conferences.",
             [("How large is the annual learning budget for each engineer?", "1,500 USD", "Each engineer has an annual learning budget of 1,500 USD")]),
        ],
    ),
    (
        "observability-standards.md", "engineering", ["engineering"], "Observability Standards",
        [
            ("Logging",
             "Services must emit structured logs in JSON format. Application logs are retained for 30 days and audit logs are retained for 400 days. Logs must never contain customer personal data.",
             [("How long are application logs retained?", "30 days", "Application logs are retained for 30 days")]),
            ("Service Level Objectives",
             "Each customer facing service defines an availability objective of at least 99.95 percent. An error budget burn alert fires when 2 percent of the monthly budget is consumed in one hour.",
             [("What is the minimum availability objective for customer facing services?", "99.95 percent", "Each customer facing service defines an availability objective of at least 99.95 percent")]),
            ("Tracing",
             "All requests carry a trace identifier in the traceparent header. Traces are sampled at 10 percent in production and 100 percent in staging.",
             [("At what rate are traces sampled in production?", "10 percent", "Traces are sampled at 10 percent in production")]),
        ],
    ),
]

# Questions the corpus does not answer: (question, collection, asking user).
UNANSWERABLE = [
    ("What is the company policy on bringing pets to the office?", "policies", "u_employee"),
    ("How many shares are granted in the employee stock purchase plan?", "policies", "u_employee"),
    ("What is the dress code for client meetings?", "policies", "u_employee"),
    ("Which airline is the preferred carrier for business class upgrades?", "policies", "u_employee"),
    ("What is the tuition reimbursement limit for graduate degrees?", "policies", "u_employee"),
    ("What is the wifi password for the guest network?", "policies", "u_employee"),
    ("Who is the Chief Executive Officer of Halden Systems?", "policies", "u_finance"),
    ("What is the relocation allowance for international transfers?", "policies", "u_finance"),
    ("What is the effective corporate tax rate for the year?", "policies", "u_finance"),
    ("Which programming language is the ledger service written in?", "engineering", "u_engineer"),
    ("Which Kubernetes version is used in production?", "engineering", "u_engineer"),
    ("What is the maximum request body size accepted by the public API?", "engineering", "u_engineer"),
]

# The user who should be able to answer questions about a document, by its ACL.
ASKER_BY_ROLE = {"employee": "u_employee", "finance": "u_finance", "engineering": "u_engineer"}
# Users who must NOT be able to retrieve a restricted document (used to derive ACL test cases).
OUTSIDERS_BY_ROLE = {"finance": ["u_employee", "u_engineer"], "engineering": ["u_employee", "u_finance"]}

# Reworded versions of some questions, phrased the way a user who has not read the document
# would ask (different vocabulary from the source sentence). These replace the literal question
# in the dataset, so lexical matching alone cannot answer them.
PARAPHRASES = {
    "Who must approve a customer refund above 2,000 USD?": "Whose sign-off is needed when we give a client back more than two thousand dollars?",
    "How many days after the invoice date can a customer request a refund?": "What is the time limit for a client to ask for their money back after being billed?",
    "How long does it take for an approved refund to be issued?": "Once giving money back has been signed off, how soon does the client get paid?",
    "How far in advance must air travel be booked?": "What lead time is required when reserving plane tickets?",
    "What is the daily meal allowance for international travel?": "How much can I spend on food per day when I am on a trip abroad?",
    "What is the deadline for submitting an expense report after a trip?": "How long do I have to file my costs once I am back from a business journey?",
    "How many days per week may employees work remotely?": "How often can staff work from home?",
    "How much is the home office stipend?": "What money does the company give me to set up a desk at home?",
    "How many days of paid annual leave do full time employees accrue per year?": "What is the yearly vacation entitlement for permanent staff?",
    "How long is parental leave for primary caregivers?": "How much time off does a new mother or main carer get after a baby arrives?",
    "When is a medical certificate required for sick leave?": "At what point do I need a note from a doctor when I am ill?",
    "What is the minimum password length?": "How long does my login passphrase need to be?",
    "How quickly must a suspected security incident be reported?": "If I think we have been hacked, how fast do I need to tell someone?",
    "What is the maximum value of a gift an employee may accept from a vendor?": "Can I keep a present from a supplier, and up to what worth?",
    "How can employees raise concerns anonymously?": "Is there a way to blow the whistle without giving my name?",
    "For how long is a new hire paired with an onboarding buddy?": "How long does a newcomer have a mentor assigned?",
    "How much of retirement contributions does the company match?": "What pension matching does the employer offer?",
    "What are the opening hours of the IT helpdesk?": "When can I reach tech support?",
    "How often are laptops replaced?": "What is the refresh cycle for company notebooks?",
    "What is the first response target for Priority 1 tickets?": "How fast do we have to reply to the most urgent customer cases?",
    "What service credit do customers get if monthly uptime falls below 99.9 percent?": "What compensation is owed to clients when availability drops under the guaranteed level?",
    "In which months do performance reviews take place?": "When during the year are staff appraisals held?",
    "How long must an employee be at their current level to be eligible for promotion?": "What tenure in grade is needed before someone can move up?",
    "How far in advance must visitors be registered?": "How early do I have to announce a guest coming to the office?",
    "How much does a parking permit cost?": "What is the monthly charge for a car space?",
    "What is the approved operating budget for fiscal year 2026?": "How much money has the company planned to spend on operations in FY2026?",
    "How many net new positions does the fiscal year 2026 plan fund?": "How many additional hires are paid for next year?",
    "What are the standard payment terms for vendors?": "How long do we take to pay suppliers?",
    "Who must approve vendor invoices above 100,000 USD?": "Whose sign-off is needed for supplier bills over one hundred thousand dollars?",
    "On what day of the month are salaries paid?": "When do staff get their wages each month?",
    "How long are payroll records retained?": "For how many years do we keep wage records?",
    "What was the revenue in the third quarter?": "How much did the company earn in sales in Q3?",
    "What was the gross margin in the third quarter?": "What gross profitability percentage was reported for Q3?",
    "How many competitive quotes are required for purchases above 25,000 USD?": "How many bids do we need to collect before buying something expensive?",
    "What is the default monthly limit on corporate cards?": "How much can be charged to a company credit card each month?",
    "How quickly must an incident commander be assigned for a SEV1 incident?": "How soon does someone have to take charge of a full outage?",
    "What is the deadline for publishing a postmortem after an incident?": "How long after an outage do we have to write up the retrospective?",
    "How many approving reviews does a production deployment require?": "How many sign-offs are needed before shipping to prod?",
    "When are production deployments frozen?": "During which period are releases to prod not allowed?",
    "At what error rate is a rollout aborted automatically?": "What failure threshold stops a staged release on its own?",
    "How long must a deprecated API version remain available?": "For how long do we keep supporting an old API version once it is sunset?",
    "What is the default API rate limit?": "How many calls can a client make before being throttled?",
    "How long are full database backups retained?": "How far back can we restore from the nightly database snapshots?",
    "Which schema migrations must be run in a maintenance window?": "When does a DDL change have to be scheduled outside normal hours?",
    "When do on call rotations hand over?": "On what day and time does pager duty change hands?",
    "What stipend do engineers receive for a week on call?": "How much extra pay is there for carrying the pager?",
    "Which service is the system of record for billing events?": "Where is the authoritative data for invoicing kept?",
    "What is the expiry of session data kept in Redis?": "How long do user sessions live in the cache?",
    "How often are credentials rotated?": "What is the renewal interval for keys and passwords used by services?",
    "How quickly must critical vulnerabilities be patched?": "What is the remediation deadline for the most severe security flaws in libraries?",
    "How much memory does the standard development laptop have?": "How much RAM do developer machines come with?",
    "How large is the annual learning budget for each engineer?": "How much money can a developer spend on training per year?",
    "How long are application logs retained?": "For how many days do we keep service log output?",
    "At what rate are traces sampled in production?": "What fraction of live requests are traced?",
}
